version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/ansi-fragments

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-website-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn test
